server:
  port: 2333
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot_db?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    include: pro
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR