server:
  port: 80
spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/girl?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/data?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    cache: false
#  profiles:
#    include: pro,mq_pro
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
    com.study.springboot: DEBUG